### ISSUE TITLE
Up version for bunyan

### ISSUE THREAD

**Issue by binarykitchen** [pwmckenna/grunt-bunyan#1]
``` js
  "peerDependencies": {
    "grunt": "~0.4.0",
    "bunyan": "~0.21.3"
  },
  "devDependencies": {
    "grunt": "~0.4.0",
    "bunyan": "~0.21.3"
  },
```

Instead of 0.21.3, can you set to 0.22.1?
https://github.com/trentm/node-bunyan/blob/master/package.json

Thx!

**Comment by pwmckenna** [comment]
would you mind publishing 0.22.1 to npm? the latest I can see there is 0.22.0.

**Comment by M165437** [comment]
Is that the reason for this error when I try installing grunt-bunyan via npm?

```
npm ERR! peerinvalid The package bunyan does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-bunyan@0.4.1 wants bunyan@~0.21.3
```

**Comment by pwmckenna** [comment]
I'm happy to set it to anything, but 0.22.0 is the version available via npm. Perhaps you haven't yet run `npm publish`?

**Comment by binarykitchen** [comment]
Huh, everyone silent? Here you go, a small PR to fix this:
https://github.com/pwmckenna/grunt-bunyan/pull/3

Also, I think I would remove peer dependencies completely. Not sure why they are here ...

**Comment by pwmckenna** [comment]
all grunt tasks should have grunt as a peer dep...grunt cli can't run unless its installed, and this grunt task is worthless unless run by grunt. bunyan is in there because its only useful if its being used for logging.
