### ISSUE TITLE
Bunyan not executing

### ISSUE THREAD

**Issue by samirprakash** [pwmckenna/grunt-bunyan#6]
Hi,

For an application using express, bunyan grunt plugin gives below error stack trace.

Grunt default task config: grunt.registerTask('default', ['jshint', 'express:dev', 'bunyan', 'watch']);

--------------------------------------------------------Error Log ------------------------------------------------------------
Running "bunyan" task

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
    at Socket._write (net.js:637:19)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at Socket.Writable.write (_stream_writable.js:182:11)
    at Socket.write (net.js:615:40)
    at WriteStream.process.stdout.write (C:\workspace\T1\b2c_aggregator\node_modules\grunt-bunyan\tasks\bunyan.js:65:31)
    at Log._write (C:\workspace\T1\b2c_aggregator\node_modules\grunt\node_modules\grunt-legacy-log\index.js:159:26)
    at Log.bound [as _write](C:workspaceT1b2c_aggregatornode_modulesgruntnode_modulesgrunt-legacy-lognode_moduleslodashdistlodash.js:729:21)
    at Log._writeln (C:\workspace\T1\b2c_aggregator\node_modules\grunt\node_modules\grunt-legacy-log\index.js:164:8)
    at Log.bound [as _writeln](C:workspaceT1b2c_aggregatornode_modulesgruntnode_modulesgrunt-legacy-lognode_moduleslodashdistlodash.js:729:21)

**Comment by pwmckenna** [comment]
@samirprakash I'm not sure what the error is about, but try moving the bunyan task before the express:dev task. The bunyan task will only filter log lines outputted by tasks after it, so you'd only get the prettyprinting for bunyan logging by the watch task. Let me know if you still end up having errors. thanks!

**Comment by samirprakash** [comment]
Thanks for the response. 

I tried your suggestion, but I am still getting the same issue. I am attaching my gruntfile for your reference. Let me know if you can help me put with the implementation.

---

/_globals require_/
module.exports = function (grunt) {
    'use strict';

```
require('load-grunt-tasks')(grunt);

grunt.initConfig({
    express: {
        dev: {
            options: {
                script: './index.js'
            }
        }
    },

    jshint: {
        files: ['GruntFile.js', 'index.js', 'app{,**/}/*.js'],
        options: {
            jshintrc: '.jshintrc',
            reporter: require('jshint-stylish')
        }
    },

    bunyan: {
        strict: true, // prevent non-bunyan logs from being outputted
        level: 'trace', // show all the things!
        output: 'short' // least verbose
    },

    watch: {
        express: {
            files: ['**/*.js'], //files to be watched
            tasks: ['express:dev', 'jshint'], //Restart the server for any changes
            options: {
                spawn: false //required for server reload
            }
        }
    }
});

grunt.registerTask('default', ['jshint', 'bunyan', 'express:dev', 'watch']);
```

};

---

Samir

**Comment by pwmckenna** [comment]
hmmm. nothing is popping out at me. try moving it before jshint, and running grunt with the --stack argument (though I'd expect we're already seeing the entire stack). also, what version of node/npm do you have installed? If I can just get a repro on me end we'll be golden...

**Comment by stephengardner** [comment]
Has this been resolved? I'm having the same issue.

Double edit: nevermind, not fixed, still an issue

**Comment by pwmckenna** [comment]
yeah, unfortunately i have no idea what's going on and not much bandwidth at the moment. I'd love a pull req if possible. Are you guys on windows?

**Comment by stephengardner** [comment]
I'm on Windows yeah

**Comment by pboffino** [comment]
I was able to make it work. I used it as it says in the README:
First i put:

```
grunt.loadNpmTasks('grunt-bunyan');
```

which I don't see in your gruntfile
and then i disposed the code as @pwmckenna said.
